### ISSUE TITLE
Actividad 3 y 4 corregida: Fallo (ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [sbeg382/UNIDAD-3#3]
En el `<head>` faltan muchos datos, por ejemplo, la descripción donde se indica el autor de la actividad. Esto ocurre en la actividad 4 también. Debería solucionarse. Puedes tomar esos datos de la actividad 1 y 2.

Otro fallo de la actividad 3 es que la función la has llamado `hola()` y debe llamarse `pedirDatos()` tal y como se indica en el PDF. En la actividad 4 sí está bien esta parte.

Cuando lo soluciones, no cierres la petición, simplemente responde a este mensaje para saber que lo has arreglado. Ya te pediré que lo cierres cuando lo revise.

**Comment by sbeg382** [comment]
Ya lo he arreglado.

**Comment by cborcar637** [comment]
Revisado. Está bien
