### ISSUE TITLE
Actividad 8 corregida: Fallo (ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [sbeg382/UNIDAD-3#7]
En programa no funciona y es porque hay varios fallos en el código.

- En la función `MensajeIf()` tienes una estructura condicional `if` donde se evalúa que la hora sea mayor de 24 y, a la vez, menor que 1. Si te fijas, nunca se va dar esa condición (no existe ningún número mayor de 24 y menor de 1). Por esta razón, el flujo de ejecución no entra nunca en la estructura `if`.
- En la función `MensajeSwitch()` se almacena el valor escrito por el usuario en la variable `hora`, pero el condicional `switch` no evalúa el valor de esa variable, sino el de la variable `respuesta`.
- Otro aspecto que no he tenido en cuenta en ninguna actividad anterior, pero que es muy importante, es tener el código tabulado para que se entienda. Existe un comando en VisualStudio que te autotabula el código, aunque yo prefiero que seáis vosotros quienes vayáis tabulando mientras vais codificando, pero bueno. El comando es `Mayúsculas + Alt + F`. Pulsa los tres botones a la vez y verás como el código HTML se organiza solo. Tabula el código HTML y el JavaScript.

Cuando soluciones estos puntos, no cierres la petición, simplemente responde a este mensaje para saber que lo has arreglado. Ya te pediré que lo cierres cuando lo revise.

**Comment by sbeg382** [comment]
Ya está corregida.

**Comment by cborcar637** [comment]
Revisado. Ahora está sin errores. Cierro la solicitud
